#!/usr/bin/env python3
"""Explicit dependency preparation for MSYS2 UCRT64 and macOS; never run by qmake."""
import argparse
from pathlib import Path
import shutil
import subprocess
import sys
import tempfile

URL = "https://github.com/qtproject/qt-solutions.git"
REVISION = "777e95ba69952f11eaec0adfb0cb987fabcdecb3"


def run(*args, cwd=None):
    subprocess.run(args, cwd=cwd, check=True)


def output(*args, cwd=None):
    return subprocess.check_output(args, cwd=cwd, text=True).strip()


def qpath(path):
    # Native Python on MSYS2 produces C:/... paths, usable by native qmake.
    value = Path(path).as_posix()
    if any(c in value for c in '\n\r"$#'):
        raise ValueError('Dependency paths must not contain newline, quote, $ or #')
    return '"' + value + '"'


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--work-dir', required=True,
                        help='dedicated directory OUTSIDE the application source tree')
    parser.add_argument('--qmake', default='qmake', help='Qt 5 qmake executable')
    parser.add_argument('--make', default='make', help='make or mingw32-make executable')
    parser.add_argument('--config', choices=('release', 'debug'), default='release')
    args = parser.parse_args()
    repo = Path(__file__).resolve().parent.parent
    work = Path(args.work_dir).expanduser().resolve()
    if work == repo or repo in work.parents:
        parser.error('--work-dir must be outside the application source tree')
    qpath(work)
    for program in ('git', args.qmake, args.make):
        if not shutil.which(program):
            parser.error('Required executable not found: ' + program)
    qt_version = output(args.qmake, '-query', 'QT_VERSION')
    if not qt_version.startswith('5.15.'):
        parser.error('Select Qt 5.15 qmake, not Qt ' + qt_version)

    work.mkdir(parents=True, exist_ok=True)
    source = work / ('qt-solutions-' + REVISION)
    if not source.exists():
        run('git', 'init', str(source))
        run('git', 'fetch', '--depth=1', URL, REVISION, cwd=source)
        run('git', 'checkout', '--detach', 'FETCH_HEAD', cwd=source)
    if output('git', 'rev-parse', 'HEAD', cwd=source) != REVISION:
        parser.error('Unexpected dependency checkout; use a fresh --work-dir')
    if output('git', 'status', '--porcelain', cwd=source):
        parser.error('Dependency checkout has local changes; use a fresh --work-dir')

    prefix = work / 'install'
    include = prefix / 'include'
    lib = prefix / 'lib'
    features = prefix / 'features'
    licenses = prefix / 'share' / 'licenses' / 'qtsingleapplication'
    for directory in (include, lib, features, licenses):
        directory.mkdir(parents=True, exist_ok=True)
    src = source / 'qtsingleapplication' / 'src'
    target = 'QtSingleApplication' + ('_debug' if args.config == 'debug' else '')
    # Build a static external library, without upstream's in-source output paths
    # or shared-library import/export macros. Qt itself remains dynamically linked.
    with tempfile.TemporaryDirectory(prefix='build-', dir=work) as temp:
        build = Path(temp)
        project = build / 'qtsingleapplication.pro'
        project.write_text(f'''TEMPLATE = lib
TARGET = {target}
QT = core gui widgets network
CONFIG -= shared dll debug release debug_and_release build_all framework
CONFIG += staticlib c++11 {args.config}
DESTDIR = $$OUT_PWD/lib
INCLUDEPATH += {qpath(src)}
SOURCES += {qpath(src / 'qtsingleapplication.cpp')} {qpath(src / 'qtlocalpeer.cpp')}
HEADERS += {qpath(src / 'qtsingleapplication.h')} {qpath(src / 'qtlocalpeer.h')}
''', encoding='utf-8')
        run(args.qmake, str(project), cwd=build)
        run(args.make, '-j2', cwd=build)
        archive = build / 'lib' / ('lib' + target + '.a')
        if not archive.is_file():
            raise RuntimeError('Expected static archive missing: ' + str(archive))
        shutil.copy2(archive, lib / archive.name)

    for name in ('qtsingleapplication.h', 'QtSingleApplication'):
        shutil.copy2(src / name, include / name)
    shutil.copy2(source / 'LICENSES' / 'BSD-3-Clause.txt', licenses)
    (licenses / 'SOURCE.txt').write_text(URL + '\n' + REVISION + '\n', encoding='utf-8')
    # PWD is the installed feature directory. No source/build paths are retained.
    (features / 'qtsingleapplication.prf').write_text('''# External static QtSingleApplication; generated by prepare-qtsingleapplication.py.
!equals(QT_MAJOR_VERSION, 5): error("QtSingleApplication was prepared for Qt 5.")
QT *= widgets network
QTSA_PREFIX = $$clean_path($$PWD/..)
QTSA_ARCHIVE = $$QTSA_PREFIX/lib/libQtSingleApplication.a
CONFIG(debug, debug|release): QTSA_ARCHIVE = $$QTSA_PREFIX/lib/libQtSingleApplication_debug.a
!exists($$QTSA_PREFIX/include/qtsingleapplication.h): error("QtSingleApplication headers are missing; rerun the preparation helper. See INSTALL.")
!exists($$QTSA_ARCHIVE): error("QtSingleApplication archive is missing for this configuration; rerun the preparation helper with --config release or --config debug. See INSTALL.")
INCLUDEPATH += $$quote($$QTSA_PREFIX/include)
LIBS += $$quote($$QTSA_ARCHIVE)
PRE_TARGETDEPS += $$quote($$QTSA_ARCHIVE)
''', encoding='utf-8')
    print('Installed QtSingleApplication at ' + str(prefix))
    print('Set QMAKEFEATURES to ' + features.as_posix())
    print('Use the same Qt, compiler, architecture and configuration for the application.')


if __name__ == '__main__':
    try:
        main()
    except (OSError, ValueError, RuntimeError, subprocess.CalledProcessError) as exc:
        sys.exit('QtSingleApplication preparation failed: ' + str(exc))
