name: Qt 5 build
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-22.04
    container: fedora:44
    strategy:
      matrix:
        compiler: [g++, clang++]
    steps:
      - name: Install dependencies
        run: |
          dnf install -y git gcc-c++ clang make pkgconf-pkg-config qt5-qtbase-devel qt5-qttools-devel qt5-qtmultimedia-devel qtsingleapplication-qt5-devel sqlite-devel libxml2-devel
      - uses: actions/checkout@v4
      - name: Build
        run: |
          mkdir _build
          cd _build
          qmake-qt5 ../QuiteRSS.pro CONFIG+=release CONFIG-=debug_and_release QMAKE_CXX=${{ matrix.compiler }} QMAKE_LINK=${{ matrix.compiler }}
          make -j2
